name: Docker CD

on:
  schedule:
    - cron: "0 0 * * TUE" # weekly update
  push:
    branches:
      - master
      - develop
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Continer Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - # イメージビルドしてGitHub Container Registry に pushする
        name: Push to GHCR
        uses: docker/build-push-action@v2
        with:
          # Dokcerfileのパス
          context: .
          push: true
          # tags: ${{ steps.docker_meta.outputs.tags }}
          tag_with_ref: true
